version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=Host=db;Port=5432;Database=taskdb;Username=taskuser;Password=taskpass
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - internal

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"  # Exposed to host for manual migration or admin tools
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - internal
      - dmz

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
  dmz:
    driver: bridge

