name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push backend
        run: |
          docker build -t youruser/backend:latest ./backend
          docker push youruser/backend:latest

      - name: Build & Push frontend
        run: |
          docker build -t youruser/frontend:latest ./frontend
          docker push youruser/frontend:latest

