name: Build & Push Docker Images (frontend + backend)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}  # your Docker Hub username

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- FRONTEND ---
      - name: Build frontend image
        run: |
          docker build \
            -t $IMAGE_NAMESPACE/frontend:latest \
            -t $IMAGE_NAMESPACE/frontend:${{ github.sha }} \
            ./frontend

      - name: Push frontend image
        run: |
          docker push $IMAGE_NAMESPACE/frontend:latest
          docker push $IMAGE_NAMESPACE/frontend:${{ github.sha }}

      # --- BACKEND ---
      - name: Build backend image
        run: |
          docker build \
            -t $IMAGE_NAMESPACE/backend:latest \
            -t $IMAGE_NAMESPACE/backend:${{ github.sha }} \
            ./backend

      - name: Push backend image
        run: |
          docker push $IMAGE_NAMESPACE/backend:latest
          docker push $IMAGE_NAMESPACE/backend:${{ github.sha }}

